apiVersion: v1
kind: Secret
metadata:
    name: openwrt-credentials
    namespace: external-dns
stringData:
    username: ENC[AES256_GCM,data:iIOigw==,iv:pDLYqxFg7zzv+MFf26ZOGGMSnzXrfdWRHOUcxUAVf84=,tag:a42/777juYLyGh3Va+aTeg==,type:str]
    password: ENC[AES256_GCM,data:kEpBGaCt0A==,iv:Ac9aqbKjQ1yJXtevzHfT1tOJnMHwk4Z3D+d3zlrQPDI=,tag:jFOeoCVjDe5X9rK7CHiNCw==,type:str]
sops:
    age:
        - recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYVIxT2hiY1ZGd0gxd1Ew
            Tm5BTjA0RjRvYnkxd2xWK2dCdUUwaFZVNGhjCk1yUTdacEhncHNhZXZFZTl4RUd4
            Zm55bnFkanQ5NzFWeXVYSFlOTG5vQ0UKLS0tIGZLcmJxalliSHIwTlg1Q2FRamlq
            VHcyTHI5Q2lvN0dITXJqenFKd2grNDAKqRFV0UtiGzGlQUZRxfQ9BwSX6jVqi8lu
            qHexGcfv5vlE+v8vYMBpBuQc2HLImGC/QHJ+AdrgZJjRvVt37A/ZvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T10:50:27Z"
    mac: ENC[AES256_GCM,data:mvb/yQ7cOc3KnSItzs0YHYdSQ3taKYuHYWaAim9Y0qEqUmjPTERXSr+qnfWKCFFCTdDr0y7QEHDJxd6CM+ruiJBJzJvlmzeZrGDnBQbs31XJnxXzIEXOAm6f9kwRTI9iNz+ZJRorl+QtSI+mJkqEGr170L31VagQXTz1K8s3kNA=,iv:YEhbL9egn6Q/5mQUkFJc6RmOdz6K90hW8g+/hZZkbLc=,tag:OOu1BfNW6WbevA9Fu4TgVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
