apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:/poFjwJ8bWgd2WDJnz8HUpEWEZp/aplwHlYQtlpbWfPH5pW2PUS8Nc1aRvFsCYn9ewI54hs=,iv:2Fkaf0TIRPt5d/bENxhAZGhRm8TidQD8U+JOJe7lODQ=,tag:6jKPqwjPPQB5uhdZmPhTsA==,type:str]
sops:
    age:
        - recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd3N0V2pUeFJCQlVEOWkv
            YlozZXBZYlhGY094ZHRHNjMyK01iQmQ4ZEU0Cnl1RXlkVElma0RBV1grbEZrODg2
            UjNPRVFjVEZhbGVkTllveWFNNE5CZHMKLS0tIGF5SG93ay9EUmRpK3VjSkN0czBq
            S21SeU8zRnZTRTBOcElCcXNOOWtZRUEKNy5bDX1E7pu7mTo3VHTmBMcWZRsLng03
            a7E+YL0rlibPyLGgsUuNZwPPqnSVi2qZVSog+mTPtz3aY9NzTqeX4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T18:33:43Z"
    mac: ENC[AES256_GCM,data:7ACjUqbd01uIREYqLmXgApGvS2N1EyoALRPDoI+PvQRsUi4nw7Gs8MFbqZA668iT2P5pcVB4bXzUc/uZhpQlArru3q1alCJuDW6BsMXv8dPMj3EuN1HyoGy37+C4+T4A6ceGoxNwMAlmJdZsZ3U0ijkLYLTZOdVA4BcdPVcFPdc=,iv:k2preePqxTXlYHrAaLUygkWvkac+9WtF03b3DQcRSzQ=,tag:/wNRwR3nMXTlFDd0PtjV1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
