apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zfs-iscsi
  namespace: democratic-csi
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      version: ">=0.14.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
      interval: 24h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    csiDriver:
      name: "org.democratic-csi.zfs-generic-iscsi"
    storageClasses:
      - name: zfs-iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
    # volumeSnapshotClasses:
    #   - name: zfs-iscsi-snapshot
    #     deletionPolicy: Delete
    driver:
      config:
        driver: zfs-generic-iscsi
        sshConnection:
          host: "192.168.30.101"
          port: 22
          username: "csi-user"
          privateKey:
            valueFrom:
              secretKeyRef:
                name: democratic-csi-ssh-key
                key: ssh-privatekey
        zfs:
          cli:
            sudoEnabled: true
            paths:
              zfs: /run/current-system/sw/bin/zfs
              zpool: /run/current-system/sw/bin/zpool
              sudo: /run/wrappers/bin/sudo
              chroot: /run/current-system/sw/bin/chroot
          datasetParentName: "rpool/k8s-data/vols"
          detachedSnapshotsDatasetParentName: "rpool/k8s/snapshots"
          zvolCompression: ""
          zvolDedup: ""
          zvolEnableReservation: false
          zvolBlocksize: ""
        iscsi:
          targetPortal: "192.168.30.101:3260"
          namePrefix: "csi-"
          nameSuffix: ""
          shareStrategy: "targetCli"
          shareStrategyTargetCli:
            sudoEnabled: true
            basename: "iqn.2003-01.org.linux-iscsi.k8s"
            tpg:
              attributes:
                authentication: 0
                generate_node_acls: 1
                demo_mode_write_protect: 0
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""
