apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-secret
    namespace: headlamp
type: Opaque
stringData:
    oidc-client-id: ENC[AES256_GCM,data:+h2ZktS8wRIKzgPHiWagz1j2dIMLMeGXypwd8HZhbZVSKDfj,iv:8MwddTBY0yw1GlNIz8vagIenbR+Okkq++TkNMm3M6Yw=,tag:zTYj7jsW4IVl5t/TRl+6QA==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:CpCGOco01rP4dfSeceBfCOJE+Q6Mc6a8CscRFUBI8eU=,iv:WmhDq/Wnomkbp34PQE0AHtSOZmR/kAvlQp4qNpvGYP8=,tag:wWqyXK/zG/CAX9bV2dNptA==,type:str]
sops:
    age:
        - recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRWcwSHJIbUxqaGdlcytl
            YzJYS3gzcytlNTB5V2p3c3d5NUNkaThiU0MwCmxrcEFLcW5tMHZWYmNhQml3RVpO
            OGs4WDdlQXRBTTJuc0pkbTlKTEtnVVEKLS0tIDQrMnFlZjdoUER2aHcyN25zL3NO
            QmJMekJaSVVweTNQOU81Nkp4R3ROQ2sKS/yltO31aewk2RdZZx3FtgSA7of1jbzQ
            CxhA+u9Yu+Ct6bhEmhvzJGDiy2R8ypSiO7u1fZ8ahhcXgS9kxYQzeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T17:43:28Z"
    mac: ENC[AES256_GCM,data:MK4HA69nORoushcJ/u17SpVlm2paKVCM8J+rp4s9bfDprOcreJZGGUYEB9+nfUkAiv07f6Mh4skUonIB1MtIR3ZDLWe1TQT1smLGHbRDak2fxWFgD5xNDQlHTnIW4DeMBG/MTd+MwvvgN2wtp0lRHL01NKICG+PtIltgV+oa3vE=,iv:8Ogofo11JlT0b1dzQVaItRamQAg4vL7RggYQbbB2gsg=,tag:/RtLb2EMPA6czSWLqVrYQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
