apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespace
patches:
  - target:
      kind: Secret
      name: regcred-rifqoi-registry-com
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: democratic-csi
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      pod-security.kubernetes.io/enforce: privileged
namespace: democratic-csi
