apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespace
patches:
  - target:
      kind: Namespace
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: testing
  - target:
      kind: Secret
      name: regcred-rifqoi-registry-com
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: testing
