# Generate JWT: pwgen -s 40 1 | base64
# Encode passwords: echo -n 'mypassword' | base64
# For production: encrypt with SOPS or kubeseal before committing
apiVersion: v1
kind: Secret
metadata:
    name: seafile-secret
    namespace: seafile
type: Opaque
stringData:
    JWT_PRIVATE_KEY: ENC[AES256_GCM,data:bn6QCSmpbfStlKTeaOvZxT8TI6CW9q3qCQInEUCqcmhpJQSZk6w75w==,iv:ZAbe696zuMpbvTjjrswP1zQgb9Y5ZfUUsH1QDvxhUjU=,tag:0HwbsHReEublgaMcZjtFwg==,type:str]
    SEAFILE_MYSQL_DB_PASSWORD: ENC[AES256_GCM,data:94tkQeX5TLlHWbe6fbrx/QY6O4pF4ol6U9qErfXN38nKJPu9QkNmhA==,iv:cxP8naL+ifd38HM9rdgqt8FpqnItsW13g1t4ykO4Vek=,tag:62tj92s8bpb9/jbUaVbndw==,type:str]
    INIT_SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:M49bmhlqXwW62PX6gw==,iv:Sp2bNgKWVopxJdc7ndxJ8FPGhDF/FKIFFRLl4s0uD14=,tag:9YyPar6fm9mkI3aRyGlvYw==,type:str]
    INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:rouz91vh5LXBv0/3odNTaGDnjw7FKKb9zDO2+4TXS7GMI21TTxn9/A==,iv:uIrEEsYXLYjuBjrdVSbRR//NCMHG+cg5xh41Dw5v0qE=,tag:bQjm+178dIHL9x871NO1AA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:lx6YYTa/SIiCLp5+,iv:BjCv4yBK2DSp/shqo0Iqt/yhbLgDxKzKPzCOnEYVhgc=,tag:KnKah6YZhosFfRV6Lm2hbw==,type:str]
sops:
    age:
        - recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVUl2RmlLN2dOUGc5MXRF
            YlpYZGdodjZYcDNZcmVSOXRUNnIzWld2QXcwCitDWkJNcmc1MHVZMzJQd3pjNEJV
            RDBFSjM1cThlRyt2ZmxKQUxqWk5sR0kKLS0tIEVHbkl5bTV1c3RBVElnU0RJSFZD
            elZjSlpzQkNoNUE5b21PNDVoUzZCb3cKiopdxZM5yCQvu84OhD6swtg0fZ25sKkm
            fudp2q05e3fWCAG1zBY1Koe6XGUHOa3kVHbu4jXhErN8nx6iimagcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T11:06:57Z"
    mac: ENC[AES256_GCM,data:jqAhvilzHCmosv0LDKxfSnrVIqswEbPDg1qVsF62OLUi3Jnz6jPQydlQwdt4Ucv1o1r/W0Pj41iJkE15GzOEwDCvCmUkoXXmRF25fTrK2ns4QxuwHyCCr9DNKfu12qmrFbiKlWjfXZBPYuo5+YUerkanbg+7BTj3zIwgtNrTRlA=,iv:un1nbxUbWKsXdkvPjRo73OWntsOi2GTqjAYFUUvDSxI=,tag:AqtJKZN3HiwF5vfbpdTcZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
