apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespace
namespace: headlamp
patches:
  - target:
      kind: Secret
      name: regcred-rifqoi-registry-com
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: headlamp
