apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany # required — shared between server + machine-learning pods
  resources:
    requests:
      storage: 100Gi
  storageClass: zfs-iscsi
