# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json
repositories:
  - name: cilium
    url: https://helm.cilium.io/
releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.18.0
    values:
      - ./values/cilium.values.yaml


