# omnictl cluster template sync -v -f cluster-template.yaml
kind: Cluster
name: talos-prod-cluster
labels:
  cluster-id: "1"
kubernetes:
  version: v1.35.0
talos:
  version: v1.12.0
patches:
  - name: disable-default-cni
    inline:
      cluster:
        network:
          cni:
            name: none
        proxy:
          disabled: true
  - name: dns-config
    inline:
      machine:
        network:
          nameservers:
            - 192.168.31.11
---
kind: ControlPlane
machineClass:
  name: libvirt-controlplane
  size: 1
systemExtensions:
  - siderolabs/qemu-guest-agent
  - siderolabs/util-linux-tools
patches:
  - name: controlplane-static-ip
    inline:
      machine:
        network:
          interfaces:
            - deviceSelector:
                busPath: "0*"
              addresses:
                - 192.168.31.200/24
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.31.1
              dhcp: false
---
kind: Workers
name: workers
machineClass:
  name: libvirt-worker
  size: 3
systemExtensions:
  - siderolabs/qemu-guest-agent
  - siderolabs/util-linux-tools
patches:
  - name: worker-labels
    inline:
      machine:
        nodeLabels:
          node-role.kubernetes.io/worker: ""
