apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nongkee
resources:
  - cluster-cnpg.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - httproute.yaml
  - secrets.enc.yaml
  - nongkee-be-pg-user-secrets.enc.yaml
