apiVersion: v1
kind: Secret
metadata:
    name: nongkee-be-pg-user
stringData:
    username: ENC[AES256_GCM,data:mpirhm7kCdKTCY7B,iv:/SBDHPfTaVEzAAbJyg2zibUAfbv+I08vyiw4z8Wc8IQ=,tag:jyC11iB/DAaD4BhuZF9zPA==,type:str]
    password: ENC[AES256_GCM,data:nIyQmEZWC8MgI8It2AJBgc9omt6+/98=,iv:1F+9GJK9ML8FphirMd5dfgQ6gCZGOv5YjSjp+Ozw1KU=,tag:91O0QNqrIN7yY307494SpQ==,type:str]
sops:
    age:
        - recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQjZKSWFoVHRMdjhlSXMr
            WVNUQ1FFbjZPa2JLaHhBY1JmeUwzNFl0QjBFCkRBdlgzZmhRM0Q4dStJRzFKcU81
            VTZiUDJadlFHbVZLelRkeGVOS1VyVEkKLS0tIG1HREFwMmV0bjFjSy9PNUZSV1BX
            VVN0cythQnVDSnFUdDd0dWxUbUd3MlUK7AkpITIte3M6GO/mEwwFqoq6j7A5tuCV
            EPYHq2Jtlq63v1TnrppA++kdolQr85EL/BoGCbL+KJCQKltYSRpjog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T13:18:46Z"
    mac: ENC[AES256_GCM,data:O4dZBmgePNwp2gMi75+Ic1QqiWsKfczvxuqjtafRTFaIZozxOdbvcvbiQrljlqx2XBnPuYSY5ra4TQmMo/o5s+XMlB7Dgtb+NjoF2YEKXrH3X1x8VRvf9VOI9/EIBee60MEIdD+r/BA9t7Aije8zrbBXnwhqa6vGA4SEMx/TLzA=,iv:5gzhx3AdaL0v/Wnsi4raz7W903fsOupLyTuZ4/uUfHQ=,tag:Hdvc1zUEneDmbHEmcvu8PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
