# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - democratic-csi
  - cloudflare-gateway
  - cilium-l2-announcements
  - cloudnative-pg
  - cert-manager
  - headlamp
  - ./secrets.enc.yaml
