apiVersion: v1
kind: Secret
metadata:
    name: my-secret
stringData:
    password: ENC[AES256_GCM,data:V7hS1PDQk9MsMI0=,iv:3+GWqWLFU/C029923+l9VaCOJcnJFCxaDkZoUzr0yF4=,tag:K2TnzpFS0yZlRev+P9zPog==,type:str]
sops:
    age:
        - recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYmgyOGpzQXUwRndJT0dQ
            Rm5oVzZxN0JzVmtYbitxRFZweDZkak5mRkdjCitXSVVDY3l2VmwyRnR6SUlQa2sv
            T21JQzV1T0NQdU94bElGS0FPam1md1EKLS0tIE1lTHo2WitWby9OOHV6L3VzditX
            dk83aVFYK1E1amNpUHRzc0pTRlppRDgKvS9ACcOO2JpeF2grcBVLKuat1mD+Kufy
            wTlkR2W1hI+76IAWFi6UT2fBwkJ7w8atf88fgOzAjeGPLMgbLzZJ3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T16:10:46Z"
    mac: ENC[AES256_GCM,data:AtJikDeRG952/emNUW3r7T3l6dNb5Kk7bRF9GuBT8sKFRi1cKZS3bc4YejzUWQfvOLGVhedwQgYsVTPEap8dkHduuaNhzPO376lF65JTxeoBEy2mXOD8nPOZaH9TZgthGBNboQuHjxgXS+bxcpjQ7UbNajjnaMCkrtMxdPfrFMg=,iv:50s17X7keZLMm8k+hQzNudJzg/i9yPNb7VQ3wCOebjY=,tag:mhnQzHuBmkkOwMg8mVTxug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
