metadata:
  namespace: default
  type: MachineClasses.omni.sidero.dev
  id: libvirt-controlplane
spec:
  autoprovision:
    providerid: libvirt
    providerdata: |
      cores: 2
      memory: 4096 # MB
      disk_size: 5368709120 # SHOULD BE IN BYTES
      storage_pool: "tank-vm"
      network_interfaces:
        - driver: bridge
          network_name: "br31"
