metadata:
  namespace: default
  type: MachineClasses.omni.sidero.dev
  id: libvirt-worker
spec:
  autoprovision:
    providerid: libvirt
    providerdata: |
      cores: 4
      memory: 6096 # MB
      disk_size: 42949672960 # bytes
      storage_pool: "tank-vm"
      network_interfaces:
        - driver: virtio
          network_name: "br31"
