metadata:
  namespace: default
  type: MachineClasses.omni.sidero.dev
  id: libvirt-worker-dev
spec:
  autoprovision:
    providerid: libvirt
    providerdata: |
      cores: 1
      memory: 2048 # MB
      disk_size: 40 # bytes
      storage_pool: "tank-vm"
      network_interfaces:
        - driver: virtio
          network_name: "br31"
