apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
  namespace: cloudflare-gateway
type: Opaque
stringData:
  ACCOUNT_ID: ENC[AES256_GCM,data:F3lMKgq5IGCHSlmWkLt375LpHAXBcyFlLqlUFJ9PbHc=,iv:3BR/RbYotUWjIhGixs97HeyEVrNUx2qA37EHNoVTumU=,tag:EHFwmm9T5IqxYzSX5nJRTA==,type:str]
  TOKEN: ENC[AES256_GCM,data:/6Xdbm+FDxYpSc5MUMVrIQmvRRq3byrFpzUAL/br+TP7s/3QOvYgv9wnZQPraHpy8EAjogg=,iv:jRwSZnyZBL/gWcHbnmp9gefIK24HW+18ptn+oPrB6Do=,tag:lQ5c1v3nT1bpd/BlHVXA8w==,type:str]
sops:
  age:
    - recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuLzdTZXR0TEtWUklPYURt
        aGQrb0xFNXJFcElQMTlSeEQ1ZHRiOWp3N1ZRCk1sT3BpZi9qaWY4QVFVNjdaRy94
        RVRrMk9kYmJRUHpaa3c4bVY4M0h4S2sKLS0tIHowb0JYOStlbkc0b25MdUpHdTlp
        Wk12cjZnaHFFTS91d3lXeitIM0Y5d3cK1jzexUa3lrxcd0TKX1SE4WfW1FU42pe1
        2CZ9M5eZ1+o5Qud9rTGAu3zerxUXaz5rm1ZtGd8F/QfJgjR5wzy+Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T17:34:09Z"
  mac: ENC[AES256_GCM,data:Mvo/xSnEd73uIaHXXhVSHbCK6JbdzPhfMobysohcTMNSKwl758dnYtEM8OpXrXFlkbsTOlbuCWd7CkykgA1sedp7z2b/WqVnn4Pl+3waPmJTMk8QME7ZZj8Mp4m9VLUO7UhYN0rw7outWCIGuHlzq+i2b1/xXtfifG+NisNfAjQ=,iv:AWUXuaB4OLvN1SM7+vSQ2beYd0CggPrrUDyhtI8w+JQ=,tag:gIOa/oOJGpBTCSSQZO64sw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
