apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: cloudflare-gateway
type: Opaque
stringData:
    ACCOUNT_ID: ENC[AES256_GCM,data:F3lMKgq5IGCHSlmWkLt375LpHAXBcyFlLqlUFJ9PbHc=,iv:3BR/RbYotUWjIhGixs97HeyEVrNUx2qA37EHNoVTumU=,tag:EHFwmm9T5IqxYzSX5nJRTA==,type:str]
    TOKEN: ENC[AES256_GCM,data:nPeZE+luRIiRnLz1p+kDDskWlov6hGUFEY7UAWj2CuKI57nIAEV2w/Ddb6qS6aMy5zkdl0w=,iv:80jbemz6IXlO7JpqRZb+poUoBwJmoe7K5rwj4oj3sPM=,tag:TxXzO7vLq0FtrEmUYSkS/Q==,type:str]
sops:
    age:
        - recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuLzdTZXR0TEtWUklPYURt
            aGQrb0xFNXJFcElQMTlSeEQ1ZHRiOWp3N1ZRCk1sT3BpZi9qaWY4QVFVNjdaRy94
            RVRrMk9kYmJRUHpaa3c4bVY4M0h4S2sKLS0tIHowb0JYOStlbkc0b25MdUpHdTlp
            Wk12cjZnaHFFTS91d3lXeitIM0Y5d3cK1jzexUa3lrxcd0TKX1SE4WfW1FU42pe1
            2CZ9M5eZ1+o5Qud9rTGAu3zerxUXaz5rm1ZtGd8F/QfJgjR5wzy+Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T17:45:53Z"
    mac: ENC[AES256_GCM,data:ybRKwU+29yhJ1SA2QT4td75trg1ID1mN5F6ot34vBIbIavsGw/6If4n8KYWBUgftHr/QprU78AhhlKskN070Q9faG+J0svgwSiP/gmTYJ2jq/gvNcnuGlrK7B1ALsv5xmjeySKgUzyMeYbORxJSBabUnxeybjhDBTOvDZOBkR64=,iv:MwHoQBMZxCY3ydXFRI+OZdT0VpsmCMbhEtH773pV/P4=,tag:lNHrT79l423xN3edCcYnPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
