apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:sO0Gs4ui0wrU+fLP+nf1kSrZVXNQAOI3okrnmvOmgvI9TXuBe7ls/4WIcnlBExHJ1eWoblVhvwi7yXtnLV8iKc5n5SrwU59LcuE/m3a++Qmp4m+OnXM4uB5ELIhJJypkS/vqM+kw6QGMbv8qsoQsuiF4sxtj/Yh92Fzm8v6m3XBaafJ/SaR0yp/DYJ5Fa4J5nVkChW/3g6iL8zNorS5fL1/whZR6h1eGyaLU7W0g0stsrHRF,iv:LNvtsbZAxJitGpL44mKXslgu8q9oJFMju0xx8zq0HdY=,tag:aofFm8MPgkPPYtttDe/s5Q==,type:str]
kind: Secret
metadata:
    name: regcred-rifqoi-registry-com
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdDdleDFVNTFDYU94ZTU3
            b0xXTDZUcVd0NjFkWCtyVEdKbERteDl3blJRCis0cDJ3N2hNQWFrN0wxV2U2Wk5h
            WFYyWHN2dFVuV0Iyd09veU01bkVFbWcKLS0tIHJJVENYcE9ha1hzcmdlbjdhK2Jh
            alVVbC82STJHUWY1MmlGR29WY09NT00K9H9nJCwJrijmpv13aRFBoteT5CeO6hv2
            yBeMBe8FJmElcDGHvioYB5/sY5RaZP7LA3kwKEgbyoek8tRmYtejgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T16:50:18Z"
    mac: ENC[AES256_GCM,data:GLxZvkYEUvAo8kAuBzmUq0SQoW91FgLTUV9iQkk4eXB3jdBYz87xxnGg7RPEY/Tt/1P9tWHPfIX9O/rMOMJiKCRYEcoiA1M/gLexZYcrF6lirEg/uUddQTBZXT+zVflmQ68sA1/bmjmw+HZvMwsuCDFN8H2LoubhabmwizGfWmU=,iv:9SO6+DbDIhOCXfviQHWqnEhwjrm2h/0sq1+ZVGGow/I=,tag:Frmfj+TsYWN6EJAUS+0xuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
